# pnpm-workspace.yaml
packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # 放置各种公用代码
  - '_public_/**'